server.port=${PORT:8080}
spring.application.name=ai-interview-platform-backend
spring.config.import=optional:application-local.properties

spring.datasource.url=${DATABASE_URL:jdbc:postgresql://ep-billowing-waterfall-ayiy0w89-pooler.c-5.us-east-2.aws.neon.tech/neondb?sslmode=require}
spring.datasource.username=${DATABASE_USER:neondb_owner}
spring.datasource.password=${DATABASE_PASSWORD:npg_o2wiTeQOEn5k}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Custom configurations
app.jwt.secret=${JWT_SECRET:dGhpcy1pcy1hLXNlY3JldC1rZXktZm9yLWp3dC10b2tlbi1nZW5lcmF0aW9uLWZvci1vdXItYWktaW50ZXJ2aWV3LXBsYXRmb3Jt}
app.jwt.expiration-ms=86400000

# Gemini API Key MUST be loaded from environment or application-local.properties to pass GitHub Push Protection
app.gemini.api-key=${GEMINI_API_KEY:}
app.gemini.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent

app.cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME:z0wrj052}
app.cloudinary.api-key=${CLOUDINARY_API_KEY:819864325921378}
app.cloudinary.api-secret=${CLOUDINARY_API_SECRET:WaLE3jgWrspYBreUcN0Q4APIhgE}

# Swagger Config
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.try-it-out-enabled=true
springdoc.swagger-ui.operations-sorter=alpha
